# Generated by Django 6.0.1 on 2026-01-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_enrollment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF/Notes')], max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_notes/')),
                ('order', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='mainapp.course')),
            ],
        ),
    ]
